debug: true

spring:
  jpa:
    hibernate:
      ddlAuto: create-drop
    show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-247-98-162.eu-west-1.compute.amazonaws.com:5432/d93qritvogevok
    username: enthctddbclyfd
    password: 338a13d7fb88d7442c7027ef6fedd8cb675f427245ee24d4f53989199380b516

server:
  port: 8090

