debug: true

spring:
  jpa:
    hibernate:
      ddlAuto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/pastoral
    username: pastoral
    password: pastoral
  h2:
    console:
      enabled: true
      path: /db


server:
  port: 8090

